cursor #a9b1d6
cursor_text_color #c0caf5

foreground            #a9b1d6
background            #1b1e2e
selection_foreground  #1b1e2e
selection_background  #73daca
url_color             #f92aad

color0   #1f2335
color1   #ff1527
color2   #64f929
color3   #ffcb15
color4   #fc29a3
color5   #730048
color6   #f92aad
color7   #ffe5f5
color8   #a18d9a
color9   #ff606c
color10  #94ff6a
color11  #ffde6a
color12  #ff4abc
color13  #ff6ac8
color14  #ff9fdb
color15  #fff4fb
